<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{{lodspk.home}}">OpenDataVis</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="{{lodspk.home}}">Home</a></li>
              <li><a href="{{lodspk.home}}latest">Latest visualizations</a></li>
              <li><a href="mailto:alvaro@graves.cl">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

