<div style="display:inline-block;">
        <button type="button" class="btn-warning btn btn-small menu-button export-dialog">
          <i class="icon-share"></i> Share this visualization
        </button>
        <button type="button" class="btn-warning btn btn-small menu-button export-dialog">
          <i class="icon-chevron-left"></i><span style='color:black;font-wight:bold;'>/</span><i class="icon-chevron-right"></i> Embed this visualization
        </button>
</div>
